replicaCount: 1

image:
  repository: shirhun/myapp
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

containerPort: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
