on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Bump Maven minor version
        id: bump
        uses: qcastel/github-actions-maven-version-bump@v1.2.0
        with:
          bump: 'minor'
          pom-file: 'backend/pom.xml'
          commit-message: 'ci: bump version to {{version}}'
          git-username: github-actions
          git-email: github-actions@github.com
      - name: Run unitests
        run: mvn test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/myapp:${{ steps.bump.outputs.version }}
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/myapp:cache
          cache-to: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/myapp:cache,mode=max